#ifndef CSC615_GROUP_TERM_PROJECT_PRAMODKHATRI10_ECHO_SENSOR_H
#define CSC615_GROUP_TERM_PROJECT_PRAMODKHATRI10_ECHO_SENSOR_H
#include <wiringPi.h>

#define TRIG 5
#define ECHO 6


void init_line_sensors();
#endif //CSC615_GROUP_TERM_PROJECT_PRAMODKHATRI10_LINE_SENSORS_H
