#ifndef CSC615_GROUP_TERM_PROJECT_PRAMODKHATRI10_ECHO_SENSOR_H
#define CSC615_GROUP_TERM_PROJECT_PRAMODKHATRI10_ECHO_SENSOR_H
#include <wiringPi.h>

#define FRONT_ECHO_SENSOR 5
#define FRONT_ECHO_TRIGGER 6


void init_line_sensors();
#endif //CSC615_GROUP_TERM_PROJECT_PRAMODKHATRI10_LINE_SENSORS_H
